name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "6.0"
    
    - name: Build
      run: swift build
    
    - name: Test
      run: swift test
    
    - name: Build Release
      run: swift build -c release
